---
Name: pp-vanilla-cookieconsent--config
---
VanillaCookieConsent\Services\CCService:
#  disable_default_css: false # Disables the default css
#  disable_default_js: false # Disables the default js
  default_lang: 'de' # Default language for the cookie consent modal
  # categories: # necessary category is added by default
  #   - analytics
  #   - marketing
  # analytics_cookie_table: # Adds a table with the cookies used for analytics (Needs to match the category) OPTIONAL
  #   _ga: '_ga_location.hostname'
  #   _gat: '_gat_location.hostname'
